apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app.kubernetes.io/name: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001


---
apiVersion: v1
kind: Service
metadata:
  name: shop
spec:
  selector:
    app.kubernetes.io/name: shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002



---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app.kubernetes.io/name: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003

