---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app_service: shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: mbehnasr2000/shop-microservice:1.0.0
          ports:
            - containerPort: 8000





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app_service: account 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: mbehnasr2000/account-microservice:1.0.0
          ports:
            - containerPort: 8000



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mbehnasr2000/order:1.0.0
          ports:
            - containerPort: 8000


