apiVersion: v1
kind: Service
metadata:
  name: shop
spec:
  type: NodePort
  selector:
    app: shop
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30009
    targetPort: 8000

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: shop
#spec:
#  selector:
#    app.kubernetes.io/name: shop
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 3002
#
#
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: order
#spec:
#  selector:
#    app.kubernetes.io/name: order
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 3003
#
