apiVersion: v1
kind: Deployment
mentadata:
  name: service-deployment
  labels:
    app: shop
spec:
  replica: 3
  selector: 
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: mbehnasr/shop-microservice:1.0.0 
          ports:
            - containerPort: 8000 
